FirstProject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

MembersManaging/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import listMembers, createMember,  updateMember, deleteMember


app_name = 'MembersManaging'


urlpatterns = [
  path('list-users/', listMembers, name = 'list-users'),
  path('create-user/', createMember, name = 'create-user'),
  path('update-user/<int:id>', updateMember, name = 'changeuser'),
  path('delete-user/<int:id>', deleteMember, name = 'deleteUser')
  
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home


app_name = 'home'


urlpatterns = [
  path('', home, name = 'home'),

  
]

MembersManaging/models.py
from django.db import models

# Create your models here.
class MembersManage(models.Model):

    name = models.CharField(max_length = 50)
    surname = models.CharField(max_length = 50)
    email = models.EmailField()
    phone = models.CharField(max_length = 20)

    def __str__(self):
        return self.name

home/models.py
from django.db import models

# Create your models here.

MembersManaging/forms.py
from .models import MembersManage
from django.forms import ModelForm


class MemberForm(ModelForm):
    class Meta:
        model = MembersManage
        fields = ['name','surname','email','phone']

MembersManaging/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import MembersManage
from .forms import MemberForm

# Create your views here.
@login_required
def listMembers(request):
    person = MembersManage.objects.all()
    print(person)
    return render(request,'Members.html',{'people':person})

@login_required
def createMember(request):
    form = MemberForm(request.POST or  None)
    if form.is_valid():
        form.save()
        
    return render(request,'newMember.html', {'form':form})

@login_required
def updateMember(request, id):
    person = get_object_or_404(MembersManage, pk = id)
    form = MemberForm(request.POST or None, instance = person)
    if form.is_valid():
        form.save() 
    return render(request, 'newMember.html',{'form':form})

@login_required
def deleteMember(request, id):
    person = get_object_or_404(MembersManage, pk = id)
    form = MemberForm(request.POST or None, instance = person)
    if request.method == 'POST':
        person.delete()
    return render(request, 'deleteMember.html',{'form':form})
    
    

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home.html')

templates/Members.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        {% for person in people %}
            <li> <a href="{% url 'MembersManaging:changeuser' person.id %}">{{ person.name }}</a>
             <a href="{% url 'MembersManaging:deleteUser' person.id %}"> Delete </a>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'MembersManaging:create-user' %}"> Novo </a>
</body>
</html>

templates/deleteMember.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <button type = "submit"> Deletar Usuario</button>
    
    </form>

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Mtv Cribs </h1>
    {% if user.is_authenticated %}
        <p> Ola {{ user.username}}</p>
        <a href="{% url 'logout' %}"> Logout </a>
    {% else %}
        <a href="{% url 'login' %}"> Login </a>
    {% endif %}
</body>
</html>

templates/newMember.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <button type = "submit">Salvar Usuario</button>
    
    </form>


    <a href="{% url 'MembersManaging:list-users' %}"> Voltar </a>
</body>
</html>